### ISSUE TITLE
Include "sparse-in-time" variables

### ISSUE THREAD

**Issue by forman** [CAB-LAB/cablab-core#12]
Some source variables, such as CCI Landcover, are provided for 5-year periods only. In total, there are three CCI LC products available. If we follow our current Cube/CubeSourceProvide approach, we would create 5 x 46 x 180 MB files with all the same data in! This is not only a waste of space. More importantly it slows down access time given the fact that value could simply be dublicated in memory.

We should introduce a concept into the Cube API that allows for generating this data on the fly when requested by users.

**Comment by mafla** [comment]
We recommend this as static variable

**Comment by forman** [comment]
Closed in favour of #48
