### ISSUE TITLE
Use h5py or xarray for Cube generation

### ISSUE THREAD

**Issue by forman** [CAB-LAB/cablab-core#38]
We currently use the netCDF4 library for opening source files which seems to have problems opening netCDF files > 6GB which is a no-go for our Air Temperature products.

We may switch to **h5py** or use **xarray** with the **h5netcd** driver to get around these problems.

See #29

**Comment by gunbra32** [comment]
The error is known and there seems to be a fix, which apparently hasn't made it through to the conda distribution. 
https://github.com/Unidata/netcdf-c/issues/188

**Comment by gunbra32** [comment]
We stick to netcdf for the time being. Downloaded source data in monthly files with two time steps per day.

**Comment by forman** [comment]
Not an issue
