### ISSUE TITLE
Missing images at the beginning of the time period

### ISSUE THREAD

**Issue by gunbra32** [CAB-LAB/cablab-core#39]
When source data is missing at the beginning of the Cube time period of interest, the resulting netcdf files of the data cube are filled with the no data value. However, the time axis is wrong in such a case. These no data images have NaN as time information.

**Comment by gunbra32** [comment]
The netcdf files of the Cube now have a valid time axis independent of the image contents.

**Comment by forman** [comment]
Fix seems to be valid
