### ISSUE TITLE
Use common land-sea mask for given cube spatial resolution

### ISSUE THREAD

**Issue by forman** [CAB-LAB/cablab-core#6]
A data provider shall have access to a common cube land-sea mask so it can decide if a variable needs to be masked before/after rescaling and regridding operations.

**Comment by forman** [comment]
Decision: we'll provide a water mask as an additional variable and let users decide what to do with it.

**Comment by forman** [comment]
We'll use the ESA CCI Water Bodies 4.0 map, available here: http://maps.elie.ucl.ac.be/CCI/viewer/

**Comment by meggart** [comment]
Can we close this issue? I think the water mask is there now?

**Comment by hans-permana** [comment]
Yes, the water mask is already available in datacube v0.2.3.
