### ISSUE TITLE
Access to the ftp server

### ISSUE THREAD

**Issue by georgeblck** [CAB-LAB/cablab-core#65]
I would like to download the ESDC data but the Brockmann ftp server that is linked in the Docs is password protected.
Is it supposed to be like that?

**Comment by hans-permana** [comment]
Hi @georgeblck, yes it is password protected.  Could you please send us an email (info@earthsystemdatacube.net) so that we can provide you with the credentials.

**Comment by HakamShams** [comment]
I want to do some experiments with ESDC data. Could you please provide me with the access to ftp server (ftp://ftp.brockmann-consult.de/cablab02/cablab-datacube-0.2.4/).

Are there any labels/annotations for extremes/anomalies in the datasets?

Thanks!
