### ISSUE TITLE
Does cube.update(Provider, path) add the variable to the cube.config file?

### ISSUE THREAD

**Issue by meggart** [CAB-LAB/cablab-core#9]
I added a dataset to an empty cube using these lines:

    cube=Cube.open(cubepath)
    cube.update(CEmissionsProvider(cube.config, sourcepath))

and it worked and produced data without throwing errors. However, afterwards the `cube.config` file in the cubepath still contains the line:

    variables = None

I was expecting this to be updated, too. Is this a bug?

**Comment by hans-permana** [comment]
The values stored in cube.config file is based on the value in CubeConfig object with the default value of 'variable' is None. The intention is to use this value to select which variables to be included when creating the cube, but at the moment it has not been implemented. That is why it shows None in the cube.config file and the cube generation still works.

**Comment by meggart** [comment]
Ah, ok then it was pure misunderstanding from my side...

**Comment by forman** [comment]
The CubeConfig object is used when the cube is created and shall remain the same during the lifetime of a data cube.
